GFORTRAN module version '6' created from long_intrinsic.junk.F90 on Mon Jul 23 16:10:43 2012
MD5:e5665c3e0a1bf044affe76d13de4536c -- If you edit this, you'll get what you deserve.

(() () () () () () () () () () () () () () () () () () () () () () ()
() () () ())

()

(('long_count' 'long_intrinsic' 2) ('long_size' 'long_intrinsic' 3 4 5 6
7 8 9 10))

()

()

()

(7 'size_j_2' 'long_intrinsic' 'size_j_2' 1 ((PROCEDURE UNKNOWN-INTENT
MODULE-PROC DECL UNKNOWN 0 0 FUNCTION IMPLICIT_PURE ALWAYS_EXPLICIT) (
INTEGER 8 0 0 INTEGER ()) 11 0 (12 13) () 14 () () () 0 0)
6 'size_r_1' 'long_intrinsic' 'size_r_1' 1 ((PROCEDURE UNKNOWN-INTENT
MODULE-PROC DECL UNKNOWN 0 0 FUNCTION IMPLICIT_PURE ALWAYS_EXPLICIT) (
INTEGER 8 0 0 INTEGER ()) 15 0 (16 17) () 18 () () () 0 0)
5 'size_r_2' 'long_intrinsic' 'size_r_2' 1 ((PROCEDURE UNKNOWN-INTENT
MODULE-PROC DECL UNKNOWN 0 0 FUNCTION IMPLICIT_PURE ALWAYS_EXPLICIT) (
INTEGER 8 0 0 INTEGER ()) 19 0 (20 21) () 22 () () () 0 0)
4 'size_d_1' 'long_intrinsic' 'size_d_1' 1 ((PROCEDURE UNKNOWN-INTENT
MODULE-PROC DECL UNKNOWN 0 0 FUNCTION IMPLICIT_PURE ALWAYS_EXPLICIT) (
INTEGER 8 0 0 INTEGER ()) 23 0 (24 25) () 26 () () () 0 0)
3 'size_d_2' 'long_intrinsic' 'size_d_2' 1 ((PROCEDURE UNKNOWN-INTENT
MODULE-PROC DECL UNKNOWN 0 0 FUNCTION IMPLICIT_PURE ALWAYS_EXPLICIT) (
INTEGER 8 0 0 INTEGER ()) 27 0 (28 29) () 30 () () () 0 0)
2 'count_l_1' 'long_intrinsic' 'count_l_1' 1 ((PROCEDURE UNKNOWN-INTENT
MODULE-PROC DECL UNKNOWN 0 0 FUNCTION IMPLICIT_PURE ALWAYS_EXPLICIT) (
INTEGER 8 0 0 INTEGER ()) 31 0 (32) () 33 () () () 0 0)
10 'size_i_1' 'long_intrinsic' 'size_i_1' 1 ((PROCEDURE UNKNOWN-INTENT
MODULE-PROC DECL UNKNOWN 0 0 FUNCTION IMPLICIT_PURE ALWAYS_EXPLICIT) (
INTEGER 8 0 0 INTEGER ()) 34 0 (35 36) () 37 () () () 0 0)
9 'size_i_2' 'long_intrinsic' 'size_i_2' 1 ((PROCEDURE UNKNOWN-INTENT
MODULE-PROC DECL UNKNOWN 0 0 FUNCTION IMPLICIT_PURE ALWAYS_EXPLICIT) (
INTEGER 8 0 0 INTEGER ()) 38 0 (39 40) () 41 () () () 0 0)
8 'size_j_1' 'long_intrinsic' 'size_j_1' 1 ((PROCEDURE UNKNOWN-INTENT
MODULE-PROC DECL UNKNOWN 0 0 FUNCTION IMPLICIT_PURE ALWAYS_EXPLICIT) (
INTEGER 8 0 0 INTEGER ()) 42 0 (43 44) () 45 () () () 0 0)
39 'array' '' 'array' 38 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
DIMENSION DUMMY) (INTEGER 4 0 0 INTEGER ()) 0 0 () (2 0 ASSUMED_SHAPE (
CONSTANT (INTEGER 8 0 0 INTEGER ()) 0 '1') () (CONSTANT (INTEGER 8 0 0
INTEGER ()) 0 '1') ()) 0 () () () 0 0)
40 'dim' '' 'dim' 38 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
OPTIONAL DUMMY) (INTEGER 4 0 0 INTEGER ()) 0 0 () () 0 () () () 0 0)
41 'mysize' '' 'mysize' 38 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN UNKNOWN 0 0 RESULT ALWAYS_EXPLICIT) (INTEGER 8 0 0 INTEGER ()) 0
0 () () 0 () () () 0 0)
35 'array' '' 'array' 34 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
DIMENSION DUMMY) (INTEGER 4 0 0 INTEGER ()) 0 0 () (1 0 ASSUMED_SHAPE (
CONSTANT (INTEGER 8 0 0 INTEGER ()) 0 '1') ()) 0 () () () 0 0)
36 'dim' '' 'dim' 34 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
OPTIONAL DUMMY) (INTEGER 4 0 0 INTEGER ()) 0 0 () () 0 () () () 0 0)
37 'mysize' '' 'mysize' 34 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN UNKNOWN 0 0 RESULT ALWAYS_EXPLICIT) (INTEGER 8 0 0 INTEGER ()) 0
0 () () 0 () () () 0 0)
43 'array' '' 'array' 42 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
DIMENSION DUMMY) (INTEGER 8 0 0 INTEGER ()) 0 0 () (1 0 ASSUMED_SHAPE (
CONSTANT (INTEGER 8 0 0 INTEGER ()) 0 '1') ()) 0 () () () 0 0)
44 'dim' '' 'dim' 42 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
OPTIONAL DUMMY) (INTEGER 4 0 0 INTEGER ()) 0 0 () () 0 () () () 0 0)
45 'mysize' '' 'mysize' 42 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN UNKNOWN 0 0 RESULT ALWAYS_EXPLICIT) (INTEGER 8 0 0 INTEGER ()) 0
0 () () 0 () () () 0 0)
12 'array' '' 'array' 11 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
DIMENSION DUMMY) (INTEGER 8 0 0 INTEGER ()) 0 0 () (2 0 ASSUMED_SHAPE (
CONSTANT (INTEGER 8 0 0 INTEGER ()) 0 '1') () (CONSTANT (INTEGER 8 0 0
INTEGER ()) 0 '1') ()) 0 () () () 0 0)
13 'dim' '' 'dim' 11 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
OPTIONAL DUMMY) (INTEGER 4 0 0 INTEGER ()) 0 0 () () 0 () () () 0 0)
14 'mysize' '' 'mysize' 11 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN UNKNOWN 0 0 RESULT ALWAYS_EXPLICIT) (INTEGER 8 0 0 INTEGER ()) 0
0 () () 0 () () () 0 0)
16 'array' '' 'array' 15 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
DIMENSION DUMMY) (REAL 4 0 0 REAL ()) 0 0 () (1 0 ASSUMED_SHAPE (
CONSTANT (INTEGER 8 0 0 INTEGER ()) 0 '1') ()) 0 () () () 0 0)
17 'dim' '' 'dim' 15 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
OPTIONAL DUMMY) (INTEGER 4 0 0 INTEGER ()) 0 0 () () 0 () () () 0 0)
18 'mysize' '' 'mysize' 15 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN UNKNOWN 0 0 RESULT ALWAYS_EXPLICIT) (INTEGER 8 0 0 INTEGER ()) 0
0 () () 0 () () () 0 0)
20 'array' '' 'array' 19 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
DIMENSION DUMMY) (REAL 4 0 0 REAL ()) 0 0 () (2 0 ASSUMED_SHAPE (
CONSTANT (INTEGER 8 0 0 INTEGER ()) 0 '1') () (CONSTANT (INTEGER 8 0 0
INTEGER ()) 0 '1') ()) 0 () () () 0 0)
21 'dim' '' 'dim' 19 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
OPTIONAL DUMMY) (INTEGER 4 0 0 INTEGER ()) 0 0 () () 0 () () () 0 0)
22 'mysize' '' 'mysize' 19 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN UNKNOWN 0 0 RESULT ALWAYS_EXPLICIT) (INTEGER 8 0 0 INTEGER ()) 0
0 () () 0 () () () 0 0)
24 'array' '' 'array' 23 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
DIMENSION DUMMY) (REAL 8 0 0 REAL ()) 0 0 () (1 0 ASSUMED_SHAPE (
CONSTANT (INTEGER 8 0 0 INTEGER ()) 0 '1') ()) 0 () () () 0 0)
25 'dim' '' 'dim' 23 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
OPTIONAL DUMMY) (INTEGER 4 0 0 INTEGER ()) 0 0 () () 0 () () () 0 0)
26 'mysize' '' 'mysize' 23 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN UNKNOWN 0 0 RESULT ALWAYS_EXPLICIT) (INTEGER 8 0 0 INTEGER ()) 0
0 () () 0 () () () 0 0)
28 'array' '' 'array' 27 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
DIMENSION DUMMY) (REAL 8 0 0 REAL ()) 0 0 () (2 0 ASSUMED_SHAPE (
CONSTANT (INTEGER 8 0 0 INTEGER ()) 0 '1') () (CONSTANT (INTEGER 8 0 0
INTEGER ()) 0 '1') ()) 0 () () () 0 0)
29 'dim' '' 'dim' 27 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
OPTIONAL DUMMY) (INTEGER 4 0 0 INTEGER ()) 0 0 () () 0 () () () 0 0)
30 'mysize' '' 'mysize' 27 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN UNKNOWN 0 0 RESULT ALWAYS_EXPLICIT) (INTEGER 8 0 0 INTEGER ()) 0
0 () () 0 () () () 0 0)
32 'array' '' 'array' 31 ((VARIABLE IN UNKNOWN-PROC UNKNOWN UNKNOWN 0 0
DIMENSION DUMMY) (LOGICAL 4 0 0 LOGICAL ()) 0 0 () (1 0 ASSUMED_SHAPE (
CONSTANT (INTEGER 8 0 0 INTEGER ()) 0 '1') ()) 0 () () () 0 0)
33 'mycount' '' 'mycount' 31 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN UNKNOWN 0 0 RESULT ALWAYS_EXPLICIT) (INTEGER 8 0 0 INTEGER ()) 0
0 () () 0 () () () 0 0)
)

()
